### ISSUE TITLE
AttributeError: 'CallbackList' object has no attribute '_set_model' - Keras 1.2.1

### ISSUE THREAD

**Issue by bear0330** [matthiasplappert/keras-rl#67]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question in the [Keras-RL Google group](https://groups.google.com/forum/#!forum/keras-rl-users) or [join the Keras-RL Gitter channel](https://gitter.im/keras-rl/Lobby) and ask there instead of filing a GitHub issue.

Thank you!

- [v] Check that you are up-to-date with the master branch of Keras-RL. You can update with:
`pip install git+git://github.com/matthiasplappert/keras-rl.git --upgrade --no-deps`

- [v] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

- [v] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). If you report an error, please include the error message and the backtrace.

While running example python ddpg_pendulum.py

**With Keras==1.2.1**

I got this error:
```
Traceback (most recent call last):
  File "ddpg_pendulum.py", line 64, in <module>
    agent.fit(env, nb_steps=50000, visualize=True, verbose=1, nb_max_episode_steps=200)
  File "C:\Miniconda2\envs\numerai\lib\site-packages\rl\core.py", line 40, in fit
    callbacks._set_model(self)
AttributeError: 'CallbackList' object has no attribute '_set_model'
```

Using Keras<1.2 works fine.

Thanks.

**Comment by gorgitko** [comment]
Yeah, I also got this error. For now just remove the leading `_` from:

https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py#L40
https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py#L42
https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py#L192
https://github.com/matthiasplappert/keras-rl/blob/master/rl/core.py#L194

**Comment by nwayt001** [comment]
It's a simple fix. In the latest version of keras (1.2.1) they changed the callback method names from '_set_model' to 'set_model' and from '_set_params' to 'set_params'.  So all you need to do is delete the leading underscore and it will work.  It's so simple, I went ahead and  made a pull request for it (#68).  I'm not sure if there are any other compatibility issues but so far I have found none.  A smarter change would be to automatically check the keras version and use the corresponding function name so that keras-rl could work with any keras version >1.0.7.

**Comment by matthiasplappert** [comment]
Has been addressed in https://github.com/matthiasplappert/keras-rl/commit/75e6c025d651f7b52d44fcee54d64c74f88d3fac and https://github.com/matthiasplappert/keras-rl/commit/e64f0634b4c53b1c18fb9faece5313c9fc6c7a7c

**Comment by unojaz** [comment]
I got the same mistake when doing a coursera problem. I then found that I missed inheriting the callback function from tf.keras.callbacks.Callback
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
         etc..etc..
